name: Docker Image Continuous Integration

on:
  push:
    branches: [ main, genai ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build command
        run: |

          echo "Using API Key: ${{ secrets.DOCKER_USERNAME }}"
          echo "Using API Secret: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/productivity_tracker:latest .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/productivity_tracker:latest